-- ================================================================
-- PMP Practice Tests: 3 Tests × 30 Questions = 90 Questions
-- ECO Domains (eco_domain column): People, Process, Business Environment
-- Categories (Performance Domain): Stakeholders, Team, Development Approach,
--   Planning, Project Work, Delivery, Measurement, Uncertainty
-- ================================================================

-- Practice Test 1
INSERT INTO exams (product_id, slug, title, time_limit_minutes, pass_threshold, status)
VALUES (13, 'pmp-practice-01', 'PMP Practice Test 01', 60, 65, 'published');
SET @exam1 = LAST_INSERT_ID();

-- Practice Test 2
INSERT INTO exams (product_id, slug, title, time_limit_minutes, pass_threshold, status)
VALUES (13, 'pmp-practice-02', 'PMP Practice Test 02', 60, 65, 'published');
SET @exam2 = LAST_INSERT_ID();

-- Practice Test 3
INSERT INTO exams (product_id, slug, title, time_limit_minutes, pass_threshold, status)
VALUES (13, 'pmp-practice-03', 'PMP Practice Test 03', 60, 65, 'published');
SET @exam3 = LAST_INSERT_ID();

-- ================================================================
-- PRACTICE TEST 01 — 30 Questions
-- ================================================================

INSERT INTO questions (exam_id, prompt, option_a, option_b, option_c, option_d, correct_answer, explanation, eco_domain, performance_domain) VALUES

(@exam1,
 'A project manager notices that two team members have a disagreement about the technical approach. What should the project manager do FIRST?',
 'Escalate the issue to the project sponsor',
 'Facilitate a discussion between the two team members to understand both perspectives',
 'Make the technical decision on behalf of the team',
 'Document the conflict in the issue log and move on',
 'B',
 'The project manager should first facilitate open dialogue between conflicting parties. Collaboration and conflict resolution are key leadership skills in the People domain.',
 'People', 'Team'),

(@exam1,
 'During sprint planning, the team identifies that a key dependency on an external vendor has not been resolved. What is the BEST course of action?',
 'Remove the dependent user stories from the sprint backlog',
 'Proceed with the sprint and hope the vendor delivers on time',
 'Escalate to the product owner and negotiate with the vendor for a commitment',
 'Cancel the sprint until the dependency is resolved',
 'C',
 'Dependencies should be actively managed. Escalating to the product owner and negotiating with the vendor addresses the impediment proactively rather than avoiding it.',
 'Process', 'Planning'),

(@exam1,
 'A stakeholder requests a major scope change halfway through the project. The change would significantly impact the timeline. What should the project manager do?',
 'Reject the change to protect the timeline',
 'Accept the change immediately to satisfy the stakeholder',
 'Evaluate the impact through the change control process and present options to the change control board',
 'Add the change to the product backlog for future consideration',
 'C',
 'All scope changes must go through the integrated change control process. The PM should assess impact and present the analysis to the CCB for a decision.',
 'Process', 'Project Work'),

(@exam1,
 'The project team is distributed across three time zones. What is the MOST effective approach to ensure collaboration?',
 'Require all team members to work during the same hours',
 'Establish overlapping core hours and use asynchronous communication tools',
 'Assign work so that no cross-timezone collaboration is needed',
 'Hold daily meetings at a time convenient only for the largest group',
 'B',
 'Overlapping core hours with asynchronous tools balance collaboration needs with respect for team members across different locations.',
 'People', 'Team'),

(@exam1,
 'A project manager is calculating Earned Value metrics. The project has a BAC of RM 500,000, PV of RM 200,000, EV of RM 180,000, and AC of RM 210,000. What is the Cost Performance Index (CPI)?',
 '0.86',
 '0.90',
 '1.17',
 '0.95',
 'A',
 'CPI = EV / AC = 180,000 / 210,000 = 0.857, rounded to 0.86. A CPI below 1.0 indicates the project is over budget.',
 'Process', 'Measurement'),

(@exam1,
 'Which of the following BEST describes the purpose of a lessons learned register?',
 'To document team performance issues for HR',
 'To capture knowledge gained during the project for future reference',
 'To track project risks and issues',
 'To record stakeholder complaints',
 'B',
 'The lessons learned register captures knowledge, experiences, and insights that can benefit current and future projects. It is a key organizational process asset.',
 'Process', 'Project Work'),

(@exam1,
 'A project sponsor asks the project manager to skip testing to meet the deadline. What should the project manager do?',
 'Comply with the sponsor request since they are the authority',
 'Explain the risks of skipping testing and propose alternatives such as phased delivery',
 'Escalate the issue to senior management',
 'Document the request and proceed without testing',
 'B',
 'The PM has a professional responsibility to communicate risks. Proposing alternatives demonstrates leadership while respecting the sponsor constraint.',
 'People', 'Delivery'),

(@exam1,
 'In an agile project, what is the PRIMARY purpose of a retrospective?',
 'To review the product increment with stakeholders',
 'To plan the next iteration',
 'To inspect the team process and identify improvements',
 'To update the project schedule',
 'C',
 'Retrospectives focus on team process improvement — what went well, what did not, and what to improve. This is distinct from sprint reviews which inspect the product.',
 'Process', 'Development Approach'),

(@exam1,
 'A project manager discovers that the project benefits outlined in the business case are no longer achievable. What should the project manager do?',
 'Continue the project and find alternative benefits',
 'Inform the sponsor and recommend a project review or termination',
 'Revise the business case independently',
 'Ignore the finding until the next phase gate',
 'B',
 'When the business case is no longer valid, the PM must inform the sponsor. The project may need to be re-evaluated or terminated to avoid wasting resources.',
 'Business Environment', 'Project Work'),

(@exam1,
 'What is the BEST way for a project manager to build trust with a new team?',
 'Set strict rules and monitor all work closely',
 'Demonstrate transparency, follow through on commitments, and empower team members',
 'Avoid showing any vulnerability or uncertainty',
 'Give the team full autonomy from day one without any guidance',
 'B',
 'Trust is built through transparency, integrity, and empowerment. Servant leadership principles emphasize supporting the team rather than controlling them.',
 'People', 'Team'),

(@exam1,
 'During project execution, a critical team member resigns unexpectedly. What should the project manager do FIRST?',
 'Immediately hire a replacement',
 'Assess the impact on the project and redistribute critical tasks',
 'Escalate to the sponsor and pause the project',
 'Ask remaining team members to work overtime',
 'B',
 'The first step is to assess the impact and ensure critical work continuity. Hiring a replacement and other actions follow the initial assessment.',
 'People', 'Team'),

(@exam1,
 'A stakeholder has been disengaged from the project despite being classified as high power and high interest. What should the project manager do?',
 'Remove the stakeholder from the communication plan',
 'Schedule one-on-one meetings to understand their concerns and re-engage them',
 'Escalate to the sponsor that the stakeholder is uncooperative',
 'Continue without the stakeholder involvement',
 'B',
 'High power, high interest stakeholders must be managed closely. The PM should proactively engage them to understand and address their concerns.',
 'People', 'Stakeholders'),

(@exam1,
 'Which technique is MOST useful for identifying the root cause of recurring quality defects?',
 'Pareto chart',
 'Fishbone (Ishikawa) diagram',
 'Control chart',
 'Scatter diagram',
 'B',
 'The fishbone diagram (cause-and-effect diagram) is specifically designed to identify root causes of problems by categorizing potential causes.',
 'Process', 'Delivery'),

(@exam1,
 'The project team has completed 60% of the work but spent 75% of the budget. Which statement is MOST accurate?',
 'The project is under budget and behind schedule',
 'The project is over budget relative to work completed',
 'The project is on track because budget was front-loaded',
 'More information is needed to determine project status',
 'B',
 'With 60% work done (EV) and 75% budget spent (AC), the CPI is less than 1 (0.8), indicating the project is over budget relative to work completed.',
 'Process', 'Measurement'),

(@exam1,
 'A new regulation requires changes to the product design. The project manager should FIRST:',
 'Implement the changes immediately as regulations are mandatory',
 'Submit a change request through the change control process',
 'Inform the sponsor and wait for direction',
 'Add the regulatory requirement to the risk register',
 'B',
 'Even mandatory changes must go through the change control process to assess impact on scope, schedule, cost, and quality before implementation.',
 'Business Environment', 'Project Work'),

(@exam1,
 'What is the PRIMARY benefit of using a hybrid project management approach?',
 'It eliminates the need for planning',
 'It combines predictive and adaptive elements to best fit the project context',
 'It guarantees faster delivery than pure agile',
 'It reduces the need for stakeholder engagement',
 'B',
 'A hybrid approach tailors elements from both predictive and adaptive methodologies to best suit the specific needs and constraints of the project.',
 'Process', 'Development Approach'),

(@exam1,
 'A project manager needs to estimate costs for a new project that is similar to a previous successful project. Which estimation technique is MOST appropriate?',
 'Bottom-up estimating',
 'Analogous estimating',
 'Three-point estimating',
 'Parametric estimating',
 'B',
 'Analogous estimating uses historical data from similar projects. It is less accurate than detailed methods but is useful when limited information is available early in the project.',
 'Process', 'Planning'),

(@exam1,
 'A team member consistently delivers work late, affecting the critical path. After private coaching, the behavior continues. What should the project manager do NEXT?',
 'Remove the team member from the project immediately',
 'Document the performance issue and escalate to the functional manager',
 'Reassign all their critical path work to other team members',
 'Accept the delays and adjust the schedule',
 'B',
 'After coaching fails, the next step is to formally document the issue and escalate to the functional manager. This follows progressive disciplinary procedures.',
 'People', 'Team'),

(@exam1,
 'What is the PRIMARY purpose of a project charter?',
 'To provide a detailed project schedule',
 'To formally authorize the project and give the PM authority to apply resources',
 'To document all project requirements',
 'To define the work breakdown structure',
 'B',
 'The project charter formally authorizes the project, names the project manager, and gives them authority to use organizational resources for project activities.',
 'Process', 'Project Work'),

(@exam1,
 'An organization is considering whether to invest in a new IT system. The project has a positive NPV of RM 2 million and an IRR of 15%. What does this indicate?',
 'The project will cost RM 2 million',
 'The project is expected to generate value exceeding its costs, adjusted for time value of money',
 'The project will take 15% longer than planned',
 'The organization cannot afford the project',
 'B',
 'A positive NPV means the project returns exceed costs when adjusted for time value of money. IRR of 15% indicates the rate of return, which should exceed the organization hurdle rate.',
 'Business Environment', 'Planning'),

(@exam1,
 'What should a servant leader project manager do when the team encounters an impediment?',
 'Assign the impediment to the most senior team member',
 'Remove the impediment or facilitate its removal to enable the team',
 'Wait for the team to solve it themselves',
 'Log it in the issue register and review it at the next status meeting',
 'B',
 'A servant leader actively removes impediments to enable the team to deliver value. This is a core principle of servant leadership in project management.',
 'People', 'Team'),

(@exam1,
 'During a project review, you discover that the project scope has been gradually expanding without formal approval. This is known as:',
 'Gold plating',
 'Scope creep',
 'Progressive elaboration',
 'Rolling wave planning',
 'B',
 'Scope creep is the uncontrolled expansion of project scope without adjustments to time, cost, and resources. It occurs when changes are not managed through formal change control.',
 'Process', 'Delivery'),

(@exam1,
 'A project team member from a different culture avoids direct eye contact and rarely speaks up in meetings. What should the project manager do?',
 'Require the team member to participate more actively in meetings',
 'Adapt the communication approach, offer alternative channels for input, and respect cultural differences',
 'Report the behavior to the team member functional manager',
 'Assume the team member is disengaged and reassign their work',
 'B',
 'Cultural sensitivity is essential. The PM should adapt communication approaches and provide multiple channels for participation to be inclusive of diverse communication styles.',
 'People', 'Stakeholders'),

(@exam1,
 'Which document links requirements to their origin and traces them through the project lifecycle?',
 'Requirements management plan',
 'Requirements traceability matrix',
 'Scope statement',
 'Work breakdown structure',
 'B',
 'The requirements traceability matrix links requirements from their origin through deliverables, ensuring each requirement adds business value and is tested.',
 'Process', 'Planning'),

(@exam1,
 'What is the MOST appropriate action when a risk identified in the risk register actually occurs?',
 'Create a new risk register entry',
 'Implement the planned risk response',
 'Conduct a new risk identification workshop',
 'Update the lessons learned and close the risk',
 'B',
 'When a risk materializes (becomes an issue), the pre-planned risk response should be implemented. This is why risk response planning is done proactively.',
 'Process', 'Uncertainty'),

(@exam1,
 'Your project has a Schedule Performance Index (SPI) of 1.2 and a Cost Performance Index (CPI) of 0.8. What does this mean?',
 'The project is ahead of schedule and under budget',
 'The project is behind schedule and over budget',
 'The project is ahead of schedule but over budget',
 'The project is behind schedule but under budget',
 'C',
 'SPI > 1 means ahead of schedule. CPI < 1 means over budget. Therefore the project is ahead of schedule but spending more than planned for the work completed.',
 'Process', 'Measurement'),

(@exam1,
 'A project manager in a matrix organization is struggling to get resources from functional managers. What is the BEST approach?',
 'Escalate immediately to the PMO',
 'Negotiate with functional managers and demonstrate how the project aligns with organizational goals',
 'Work only with available resources regardless of skill requirements',
 'Ask the sponsor to mandate resource allocation',
 'B',
 'In a matrix organization, negotiation and influence are essential. Showing alignment with organizational goals is the most effective long-term strategy for securing resources.',
 'Business Environment', 'Team'),

(@exam1,
 'What is the PRIMARY purpose of a burndown chart in an agile project?',
 'To track team velocity over multiple sprints',
 'To show the remaining work in the sprint or release and track progress',
 'To identify resource utilization',
 'To compare planned vs actual costs',
 'B',
 'A burndown chart displays the amount of work remaining over time, making it easy to visualize whether the team is on track to complete the planned work.',
 'Process', 'Measurement'),

(@exam1,
 'A project manager identifies that a key stakeholder has been providing conflicting requirements. What should the project manager do?',
 'Accept the most recent requirement and discard the previous one',
 'Facilitate a stakeholder alignment session to resolve conflicts and document agreed requirements',
 'Choose the requirement that is easiest to implement',
 'Ask the sponsor to decide which requirement is correct',
 'B',
 'The PM should facilitate discussion among stakeholders to resolve conflicting requirements. This promotes consensus and ensures all perspectives are considered.',
 'People', 'Stakeholders'),

(@exam1,
 'Which risk response strategy involves shifting the negative impact of a risk to a third party?',
 'Avoid',
 'Mitigate',
 'Transfer',
 'Accept',
 'C',
 'Risk transfer shifts the impact of a risk to a third party, such as through insurance, warranties, or outsourcing. The risk is not eliminated, only the management responsibility shifts.',
 'Process', 'Uncertainty');


-- ================================================================
-- PRACTICE TEST 02 — 30 Questions
-- ================================================================

INSERT INTO questions (exam_id, prompt, option_a, option_b, option_c, option_d, correct_answer, explanation, eco_domain, performance_domain) VALUES

(@exam2,
 'A new team member joins mid-project and struggles to understand the project context. What should the project manager do?',
 'Provide the team member with the project charter, WBS, and relevant documentation and assign a mentor',
 'Tell the new member to review emails and catch up independently',
 'Reduce the new team member responsibilities until the next phase',
 'Postpone onboarding until the current iteration is complete',
 'A',
 'Effective onboarding includes providing key project documents and assigning a mentor. This helps new members ramp up quickly and contribute meaningfully.',
 'People', 'Team'),

(@exam2,
 'A project is using Kanban for workflow management. The team notices a bottleneck at the testing stage. What should the team do FIRST?',
 'Add more testers to the team immediately',
 'Analyze the root cause of the bottleneck and adjust WIP limits',
 'Skip testing for low-risk features',
 'Move testing to a separate team outside the Kanban board',
 'B',
 'In Kanban, bottlenecks should be analyzed to understand root causes. Adjusting WIP (Work In Progress) limits and improving flow is the proper first response.',
 'Process', 'Delivery'),

(@exam2,
 'Your organization has a PMO that mandates the use of a specific project management methodology. However, your project would benefit from a different approach. What should you do?',
 'Follow the mandated methodology exactly as required',
 'Discuss your concerns with the PMO and propose a tailored approach with justification',
 'Ignore the PMO guidelines and use the approach you prefer',
 'Escalate directly to senior management without consulting the PMO',
 'B',
 'A professional PM should engage the PMO constructively, presenting evidence for why a tailored approach would benefit the project. This respects governance while advocating for the project.',
 'Business Environment', 'Development Approach'),

(@exam2,
 'What is the MOST important factor when selecting a development approach for a project?',
 'The project manager personal preference',
 'The project characteristics, organizational culture, and degree of uncertainty',
 'The latest industry trends',
 'The tools available to the team',
 'B',
 'The development approach should be selected based on project context — including uncertainty level, requirements stability, organizational culture, and team capabilities.',
 'Process', 'Development Approach'),

(@exam2,
 'A project manager is asked to deliver a project with an unrealistic deadline set by senior management. What should the project manager do?',
 'Accept the deadline and push the team to meet it',
 'Present data showing the realistic timeline, identify risks, and propose options such as scope reduction or phased delivery',
 'Refuse to accept the project',
 'Agree to the deadline and plan to request an extension later',
 'B',
 'The PM should use evidence-based arguments to present realistic alternatives. Proposing options demonstrates leadership while respecting organizational constraints.',
 'People', 'Planning'),

(@exam2,
 'In the PMBOK framework, what is the difference between a project and operations?',
 'Projects are always larger than operations',
 'Projects are temporary with unique deliverables while operations are ongoing and repetitive',
 'Operations require more resources than projects',
 'Projects do not require a budget while operations do',
 'B',
 'A project is a temporary endeavor to create a unique product, service, or result. Operations are ongoing, repetitive activities that sustain the business.',
 'Business Environment', 'Project Work'),

(@exam2,
 'A project has multiple stakeholders with competing interests. What tool can help the project manager prioritize stakeholder engagement?',
 'RACI matrix',
 'Power/Interest grid',
 'Work breakdown structure',
 'Gantt chart',
 'B',
 'The Power/Interest grid (stakeholder mapping) helps classify stakeholders based on their power and interest levels, enabling the PM to prioritize engagement strategies.',
 'People', 'Stakeholders'),

(@exam2,
 'The team velocity has been declining over the past three sprints. What should the agile project manager investigate FIRST?',
 'Whether the user stories are properly sized',
 'Whether there are team morale issues, impediments, or process problems',
 'Whether the product backlog is properly prioritized',
 'Whether the sprint duration should be shortened',
 'B',
 'Declining velocity often points to team issues — morale, impediments, or process problems. The scrum master/PM should investigate root causes through retrospectives.',
 'People', 'Measurement'),

(@exam2,
 'What is the purpose of the project management plan?',
 'To list all project activities in chronological order',
 'To define how the project is executed, monitored, controlled, and closed',
 'To document the project budget only',
 'To serve as a contract between the PM and the sponsor',
 'B',
 'The project management plan is a comprehensive document that defines how the project will be executed, monitored, controlled, and closed. It integrates all subsidiary plans.',
 'Process', 'Planning'),

(@exam2,
 'A team member reports that they feel micromanaged and it is affecting their productivity. What should the project manager do?',
 'Continue the current management style as it ensures quality',
 'Reflect on their management approach, discuss with the team member, and adjust to provide more autonomy while maintaining accountability',
 'Assign the team member to tasks that require less oversight',
 'Ask other team members if they feel the same way before making changes',
 'B',
 'Self-reflection and adjusting leadership style based on team feedback demonstrates emotional intelligence. Balancing autonomy with accountability is a key leadership skill.',
 'People', 'Team'),

(@exam2,
 'Which of the following is a key output of the Plan Risk Management process?',
 'Risk register',
 'Risk management plan',
 'Risk response strategies',
 'Monte Carlo simulation results',
 'B',
 'The Plan Risk Management process produces the risk management plan, which defines how risk activities will be structured and performed throughout the project.',
 'Process', 'Uncertainty'),

(@exam2,
 'A project manager notices that deliverables are not meeting quality standards despite passing all individual tests. What might be the issue?',
 'The tests are too lenient',
 'Integration testing between components is insufficient',
 'The quality standards are unrealistic',
 'The team lacks technical skills',
 'B',
 'When individual components pass but overall quality suffers, the issue is often insufficient integration testing. Components must work together as a system.',
 'Process', 'Delivery'),

(@exam2,
 'What is the BEST way to handle a situation where the project sponsor and a key stakeholder have fundamentally different expectations for the project outcome?',
 'Align with the sponsor expectations since they have higher authority',
 'Facilitate a stakeholder alignment meeting to find common ground and document agreed expectations',
 'Let the conflict resolve itself over time',
 'Deliver separate reports to each showing their preferred version',
 'B',
 'Stakeholder conflicts about project expectations need to be addressed directly through facilitated discussions. Finding common ground ensures project success.',
 'People', 'Stakeholders'),

(@exam2,
 'Your project critical path has zero float. What does this mean?',
 'The project has no risks',
 'Any delay on the critical path will delay the entire project',
 'The project is behind schedule',
 'Resources are fully utilized',
 'B',
 'Zero float on the critical path means there is no schedule flexibility — any delay in a critical path activity will directly delay the project completion date.',
 'Process', 'Planning'),

(@exam2,
 'A project manager is working with a team that has never used agile before. What approach is MOST appropriate?',
 'Implement full Scrum framework immediately',
 'Start with a few agile practices and gradually introduce more as the team gains comfort',
 'Skip agile and use waterfall since the team is unfamiliar',
 'Send the entire team to agile certification before starting',
 'B',
 'Gradually introducing agile practices allows the team to adapt without being overwhelmed. This iterative approach to adopting agile itself leads to more sustainable change.',
 'People', 'Development Approach'),

(@exam2,
 'What is the main purpose of a project kickoff meeting?',
 'To assign all project tasks',
 'To align stakeholders on project objectives, approach, roles, and expectations',
 'To finalize the project budget',
 'To approve the project charter',
 'B',
 'The kickoff meeting brings stakeholders together to establish a shared understanding of the project objectives, approach, roles, communication plans, and expectations.',
 'Process', 'Project Work'),

(@exam2,
 'A project manager needs to compress the schedule without changing scope. Which technique involves adding resources to critical path activities?',
 'Fast tracking',
 'Crashing',
 'Lead and lag adjustments',
 'Resource leveling',
 'B',
 'Crashing adds resources to critical path activities to shorten their duration. It typically increases cost but maintains scope. Fast tracking runs activities in parallel.',
 'Process', 'Planning'),

(@exam2,
 'An organization is evaluating multiple potential projects. Which tool helps select projects that best align with strategic objectives?',
 'Critical path method',
 'Weighted scoring model or portfolio analysis',
 'Earned value analysis',
 'Delphi technique',
 'B',
 'Weighted scoring models and portfolio analysis help organizations evaluate and prioritize projects against strategic criteria, ensuring the best allocation of resources.',
 'Business Environment', 'Project Work'),

(@exam2,
 'During a sprint review, a stakeholder requests a significant new feature. What should the Scrum team do?',
 'Add it to the current sprint immediately',
 'Add it to the product backlog for prioritization by the Product Owner',
 'Reject it outright since the sprint is ending',
 'Promise to deliver it in the next sprint',
 'B',
 'New feature requests should be added to the product backlog. The Product Owner will prioritize it against other items. Never commit to delivering it in a specific sprint without planning.',
 'Process', 'Delivery'),

(@exam2,
 'What is the PRIMARY advantage of using a Work Breakdown Structure (WBS)?',
 'It identifies the project critical path',
 'It decomposes the total scope into manageable work packages ensuring nothing is missed',
 'It assigns resources to tasks',
 'It tracks actual costs against the budget',
 'B',
 'The WBS decomposes total project scope into smaller, manageable components. It ensures 100% of the scope is captured and provides a foundation for planning.',
 'Process', 'Planning'),

(@exam2,
 'A project manager learns that a vendor critical to the project is experiencing financial difficulties. What should the PM do?',
 'Terminate the vendor contract immediately',
 'Assess the risk, develop contingency plans, and monitor the vendor situation closely',
 'Ignore the information as it is outside the project scope',
 'Switch to a new vendor without informing the team',
 'B',
 'Vendor financial issues represent a project risk. The PM should assess impact, develop contingency plans (backup vendors), and monitor the situation proactively.',
 'Process', 'Uncertainty'),

(@exam2,
 'In emotional intelligence, what does self-regulation refer to?',
 'Controlling how you react to situations and managing disruptive emotions',
 'Understanding other people emotions',
 'Motivating yourself to achieve goals',
 'Building strong interpersonal relationships',
 'A',
 'Self-regulation is the ability to control or redirect disruptive impulses and moods, and to think before acting. It is one of the five components of emotional intelligence.',
 'People', 'Team'),

(@exam2,
 'What type of contract places the MOST risk on the seller?',
 'Cost Plus Fixed Fee (CPFF)',
 'Time and Materials (T&M)',
 'Firm Fixed Price (FFP)',
 'Cost Plus Incentive Fee (CPIF)',
 'C',
 'A Firm Fixed Price contract places maximum risk on the seller because they must deliver at the agreed price regardless of their actual costs.',
 'Process', 'Uncertainty'),

(@exam2,
 'A project manager discovers that the actual cost of work performed significantly exceeds the earned value. Which metric highlights this?',
 'Schedule Variance (SV)',
 'Cost Variance (CV)',
 'Variance at Completion (VAC)',
 'To-Complete Performance Index (TCPI)',
 'B',
 'Cost Variance (CV = EV - AC) shows the difference between earned value and actual cost. A negative CV indicates the project is over budget for work completed.',
 'Process', 'Measurement'),

(@exam2,
 'Your team is demotivated because they feel the project lacks purpose. According to motivational theory, what should you emphasize?',
 'Financial bonuses for meeting milestones',
 'The project value to end users and the organization strategic goals',
 'Strict deadlines to create urgency',
 'Competitive ranking among team members',
 'B',
 'Intrinsic motivation through purpose is more sustainable than extrinsic rewards. Connecting the work to meaningful outcomes increases team engagement and morale.',
 'People', 'Team'),

(@exam2,
 'What should a project manager do when a previously identified risk has a higher probability than initially assessed?',
 'Accept the risk since it was already identified',
 'Re-evaluate the risk, update the risk register, and adjust the response strategy if needed',
 'Escalate the risk to the sponsor without further analysis',
 'Remove the risk from the register and create a new entry',
 'B',
 'Risk management is iterative. When risk probability changes, the PM should re-evaluate, update the register, and potentially modify the response strategy.',
 'Process', 'Uncertainty'),

(@exam2,
 'A project operates in an industry with strict regulatory compliance requirements. How should the project manager address this?',
 'Treat compliance as a separate workstream outside the project',
 'Integrate compliance requirements into the project scope, quality criteria, and deliverable acceptance criteria',
 'Leave compliance to the legal department',
 'Address compliance during the closing phase',
 'B',
 'Regulatory compliance must be integrated throughout the project lifecycle — in scope definition, quality criteria, and acceptance criteria. Leaving it to closing phase is too late.',
 'Business Environment', 'Delivery'),

(@exam2,
 'What communication method is MOST effective for conveying complex or sensitive information to a stakeholder?',
 'Email with attachments',
 'Face-to-face or video call with supporting materials',
 'Status report distributed to all stakeholders',
 'Instant messaging',
 'B',
 'Complex or sensitive information is best conveyed through rich, interactive communication channels like face-to-face meetings or video calls that allow for immediate feedback.',
 'People', 'Stakeholders'),

(@exam2,
 'During project closure, the PM notices that some deliverables were accepted informally without proper sign-off. What should the PM do?',
 'Close the project since the deliverables were accepted',
 'Obtain formal acceptance documentation for all deliverables before final closure',
 'Note it in the lessons learned and proceed',
 'Re-deliver all informally accepted items',
 'B',
 'Formal acceptance of deliverables is a required part of project closure. The PM should obtain proper sign-off to ensure all parties agree the deliverables meet acceptance criteria.',
 'Process', 'Delivery'),

(@exam2,
 'A project manager is establishing metrics for project success. Beyond the traditional triple constraint, which metric is increasingly important?',
 'Number of change requests',
 'Benefits realization and stakeholder satisfaction',
 'Number of resources used',
 'Lines of code produced',
 'B',
 'Modern project management emphasizes outcomes over outputs. Benefits realization (did the project deliver expected value?) and stakeholder satisfaction are critical success metrics.',
 'Business Environment', 'Measurement');


-- ================================================================
-- PRACTICE TEST 03 — 30 Questions
-- ================================================================

INSERT INTO questions (exam_id, prompt, option_a, option_b, option_c, option_d, correct_answer, explanation, eco_domain, performance_domain) VALUES

(@exam3,
 'A product owner continuously changes priorities every sprint, causing confusion and rework. What should the project manager do?',
 'Ignore the changes and follow the original plan',
 'Discuss the impact of frequent changes with the product owner and negotiate a more stable sprint commitment',
 'Escalate to senior management to override the product owner',
 'Let the team decide which changes to accept',
 'B',
 'The PM/Scrum Master should have an open discussion with the product owner about the impact of constant reprioritization. Sprint goals should be respected once committed.',
 'People', 'Stakeholders'),

(@exam3,
 'What is the PRIMARY benefit of conducting a pre-mortem analysis at the start of a project?',
 'It replaces the need for risk management throughout the project',
 'It helps the team identify potential failure points before they occur',
 'It provides stakeholders with a guarantee of project success',
 'It eliminates all uncertainty from the project',
 'B',
 'A pre-mortem asks the team to imagine the project has failed and identify what caused the failure. This proactive approach surfaces risks and assumptions early.',
 'Process', 'Uncertainty'),

(@exam3,
 'A team is transitioning from traditional waterfall to agile methodology. What is the BIGGEST challenge likely to be faced?',
 'Learning new software tools',
 'Cultural shift and mindset change from command-and-control to self-organization',
 'Shorter meeting durations',
 'Reduced documentation requirements',
 'B',
 'The biggest challenge in agile transitions is the cultural change — moving from hierarchical management to empowered, self-organizing teams requires a fundamental mindset shift.',
 'People', 'Development Approach'),

(@exam3,
 'What is the difference between quality assurance and quality control?',
 'Quality assurance is performed by the QA team while quality control is done by developers',
 'Quality assurance focuses on preventing defects through process improvement while quality control focuses on detecting defects through inspection',
 'Quality assurance is more important than quality control',
 'Quality control is proactive while quality assurance is reactive',
 'B',
 'QA is process-oriented and proactive (preventing defects by improving processes). QC is product-oriented and reactive (detecting defects through testing and inspection).',
 'Process', 'Delivery'),

(@exam3,
 'A project manager is managing a project with a tight budget. The team proposes using open-source tools instead of licensed software. What factor is MOST important to evaluate?',
 'The popularity of the open-source tool',
 'The total cost of ownership including support, compatibility, security, and maintenance',
 'Whether the team has used the tool before',
 'The number of downloads of the open-source tool',
 'B',
 'Total cost of ownership considers not just the license cost savings but also support availability, security updates, compatibility, and long-term maintenance costs.',
 'Business Environment', 'Planning'),

(@exam3,
 'A virtual team member is underperforming, and the project manager suspects the issue is isolation. What is the BEST approach?',
 'Replace the team member with someone co-located',
 'Increase check-ins, pair them with a buddy, and create social interaction opportunities',
 'Set stricter deadlines to motivate them',
 'Send a formal warning about performance expectations',
 'B',
 'Remote team members may struggle with isolation. Increasing touchpoints, buddy systems, and social interactions address the root cause rather than symptoms.',
 'People', 'Team'),

(@exam3,
 'Which diagram shows the order and dependencies between project activities?',
 'Work Breakdown Structure',
 'Precedence Diagramming Method (PDM) / Network Diagram',
 'Organizational Breakdown Structure',
 'Responsibility Assignment Matrix',
 'B',
 'The PDM (network diagram) shows the sequence of activities and their dependencies (finish-to-start, start-to-start, etc.), which is essential for schedule development.',
 'Process', 'Planning'),

(@exam3,
 'A stakeholder is actively trying to undermine the project by spreading misinformation. What should the project manager do?',
 'Confront the stakeholder publicly in a meeting',
 'Address the situation privately with the stakeholder, understand their concerns, and involve the sponsor if needed',
 'Ignore the behavior and focus on the project',
 'Exclude the stakeholder from all future communications',
 'B',
 'Negative stakeholder behavior should be addressed professionally and privately. Understanding their concerns may reveal legitimate issues. The sponsor should be involved if needed.',
 'People', 'Stakeholders'),

(@exam3,
 'What is the PRIMARY purpose of a Definition of Done (DoD) in an agile project?',
 'To define when the project is complete',
 'To establish a shared understanding of the quality criteria that must be met before a work item is considered complete',
 'To set the sprint duration',
 'To define the acceptance criteria for user stories',
 'B',
 'The Definition of Done is a team agreement on quality criteria (code review, testing, documentation, etc.) that must be met before any increment is considered complete.',
 'Process', 'Delivery'),

(@exam3,
 'You are a project manager in a weak matrix organization. What is your PRIMARY challenge?',
 'Having too much authority over resources',
 'Having limited formal authority and needing to rely on influence and negotiation to get things done',
 'Managing a budget that is too large',
 'Dealing with too many project sponsors',
 'B',
 'In a weak matrix, functional managers have more authority than project managers. PMs must rely on influence, negotiation, and interpersonal skills to manage resources.',
 'Business Environment', 'Team'),

(@exam3,
 'A project team is distributed across multiple countries with significant cultural differences. The PM has scheduled a team-building event. What is the MOST important consideration?',
 'Keeping the event within budget',
 'Ensuring the activity is culturally inclusive and respectful of all team members backgrounds',
 'Scheduling at a time convenient for the PM',
 'Making the event competitive to motivate performance',
 'B',
 'Cultural sensitivity is critical for virtual/distributed teams. Team-building activities must be inclusive and respectful of diverse backgrounds, religions, and customs.',
 'People', 'Team'),

(@exam3,
 'A project has a high number of unknown risks due to innovative technology. Which development approach is MOST suitable?',
 'Predictive (waterfall) with extensive upfront planning',
 'Adaptive (agile) with iterative development and frequent feedback loops',
 'No specific approach — ad hoc management',
 'Hybrid with mostly predictive elements',
 'B',
 'High uncertainty environments benefit from adaptive approaches that allow learning through iteration, frequent feedback, and course corrections based on new information.',
 'Process', 'Development Approach'),

(@exam3,
 'A project manager receives feedback that status reports are too detailed for executive stakeholders. What should the PM do?',
 'Continue with detailed reports as they are thorough',
 'Tailor communication by creating executive summaries with key metrics and escalation items',
 'Stop sending reports to executives',
 'Ask executives to specify exactly what they want in each report',
 'B',
 'Communication should be tailored to the audience. Executives typically need high-level summaries with key decisions, risks, and metrics — not operational details.',
 'People', 'Stakeholders'),

(@exam3,
 'What does the project Estimate at Completion (EAC) represent?',
 'The original total budget for the project',
 'The expected total cost of the project based on current performance',
 'The remaining budget available',
 'The planned value of all project work',
 'B',
 'EAC is the forecasted total cost of completing the project, calculated using current performance data. It revises the original BAC based on actual performance trends.',
 'Process', 'Measurement'),

(@exam3,
 'A project manager wants to implement earned value management but the team is unfamiliar with it. What is the BEST approach?',
 'Implement it fully and let the team learn on the job',
 'Provide training on EVM concepts and start with basic metrics (CPI, SPI) before introducing advanced measures',
 'Skip EVM and use simple progress tracking',
 'Hire an EVM specialist as a consultant',
 'B',
 'Gradual introduction of EVM with training ensures the team understands and can use the metrics effectively. Starting with basic CPI/SPI provides immediate value.',
 'Process', 'Measurement'),

(@exam3,
 'During project execution, you realize the original risk assessment significantly underestimated several risks. What should you do?',
 'Add budget contingency and continue',
 'Conduct a comprehensive risk reassessment, update the risk register, and adjust risk responses and management reserves',
 'Focus on the risks that have already materialized',
 'Inform the sponsor that the project will be delayed',
 'B',
 'When risk assessments prove significantly inaccurate, a comprehensive reassessment is needed. All risk responses and reserves should be reviewed and adjusted.',
 'Process', 'Uncertainty'),

(@exam3,
 'What is the MOST effective way to manage stakeholder expectations throughout the project?',
 'Only communicate when there is good news',
 'Provide regular, transparent updates on progress, risks, and issues through agreed communication channels',
 'Delegate stakeholder management to the project coordinator',
 'Set low expectations at the beginning to make the project look successful',
 'B',
 'Transparent, regular communication through agreed channels builds trust and helps manage expectations. Hiding bad news erodes stakeholder confidence long term.',
 'People', 'Stakeholders'),

(@exam3,
 'A project team is using a predictive approach but discovers that requirements are evolving significantly. What should the project manager recommend?',
 'Freeze requirements and reject any further changes',
 'Assess whether transitioning to an adaptive or hybrid approach would better serve the project',
 'Continue with the predictive approach and add a change control board',
 'Restart the project with an agile framework',
 'B',
 'When requirements evolve significantly in a predictive project, the PM should evaluate whether switching to an adaptive or hybrid approach would be more effective.',
 'Process', 'Development Approach'),

(@exam3,
 'A critical project resource is shared between your project and another project, creating conflicts. What is the BEST long-term solution?',
 'Demand exclusive access to the resource',
 'Work with the other project manager and resource manager to create a shared resource schedule and escalate if needed',
 'Find a replacement resource within your team',
 'Accept reduced productivity from the shared resource',
 'B',
 'Resource conflicts between projects should be managed collaboratively. Working with peers and resource managers to create a shared schedule is the most professional approach.',
 'People', 'Planning'),

(@exam3,
 'What is psychological safety in the context of a project team?',
 'Ensuring team members have a safe physical work environment',
 'Creating an environment where team members feel safe to take risks, share ideas, and admit mistakes without fear of punishment',
 'Providing mental health benefits to all team members',
 'Ensuring no one works overtime',
 'B',
 'Psychological safety means team members can speak up, take risks, and make mistakes without fear of embarrassment or punishment. It is essential for innovation and learning.',
 'People', 'Team'),

(@exam3,
 'A project manager identifies that the organization lacks the technical capabilities needed for a project deliverable. What should the PM recommend?',
 'Cancel the project due to insufficient capability',
 'Evaluate options including training, hiring, outsourcing, or partnering and recommend the most viable approach',
 'Proceed with existing capabilities and hope for the best',
 'Reduce the project scope to match existing capabilities',
 'B',
 'A capability gap should be addressed through analysis of options. Training, hiring, outsourcing, or partnerships are all valid strategies depending on timeline and budget.',
 'Business Environment', 'Project Work'),

(@exam3,
 'What is the main benefit of using a RACI matrix on a project?',
 'It tracks project costs',
 'It clarifies roles and responsibilities to prevent confusion and ensure accountability',
 'It identifies project risks',
 'It shows the project schedule',
 'B',
 'The RACI matrix assigns Responsible, Accountable, Consulted, and Informed roles for each deliverable/activity, preventing confusion and ensuring clear accountability.',
 'Process', 'Team'),

(@exam3,
 'A project is behind schedule. The PM identifies that fast-tracking two parallel activities could recover the delay. What risk does fast-tracking introduce?',
 'Increased cost due to additional resources',
 'Increased risk of rework because of parallel activities that may have dependencies',
 'Reduced team morale',
 'Scope reduction',
 'B',
 'Fast-tracking runs activities in parallel that were originally planned sequentially. This increases risk of rework if the parallel activities have hidden dependencies.',
 'Process', 'Planning'),

(@exam3,
 'A project is delivering a new system that will change how employees do their work. What should the project manager ensure is included in the project plan?',
 'Only technical deployment steps',
 'An organizational change management plan including communication, training, and stakeholder support',
 'A plan to replace employees who resist the change',
 'A bonus program for early adopters',
 'B',
 'Projects that change how people work need organizational change management — communication, training, support systems, and stakeholder engagement to ensure adoption.',
 'Business Environment', 'Delivery'),

(@exam3,
 'What is the MOST appropriate way to handle a situation where a team cannot agree on a technical solution?',
 'The PM should make the decision since they are the authority',
 'Facilitate an evaluation of options using agreed criteria and let the team reach consensus or use a decision-making technique',
 'Bring in an external consultant to decide',
 'Assign the decision to the most senior team member',
 'B',
 'The PM should facilitate decision-making using agreed criteria. Techniques like multi-criteria decision analysis help teams evaluate options objectively and reach consensus.',
 'People', 'Team'),

(@exam3,
 'What is the significance of the project management triangle (triple constraint)?',
 'It shows the three phases of a project',
 'It illustrates that scope, schedule, and cost are interrelated and changes to one affect the others',
 'It identifies the three types of project risks',
 'It defines the three levels of project authority',
 'B',
 'The triple constraint shows that scope, schedule, and cost are interconnected. Changing one typically impacts the others, requiring trade-off decisions.',
 'Process', 'Project Work'),

(@exam3,
 'An agile team has been performing well but suddenly starts missing sprint commitments. What should the scrum master investigate?',
 'Whether the team is spending too much time in retrospectives',
 'Whether team dynamics have changed, impediments exist, or story points are being overcommitted',
 'Whether the product backlog needs to be re-estimated',
 'Whether the sprint should be extended',
 'B',
 'When a previously well-performing team starts missing commitments, the root causes are typically team dynamics changes, unresolved impediments, or overcommitment.',
 'People', 'Measurement'),

(@exam3,
 'What is the difference between a milestone and a deliverable?',
 'There is no difference — they are the same thing',
 'A milestone is a significant point or event in the project while a deliverable is a tangible output produced by the project',
 'A deliverable must be approved while a milestone does not',
 'Milestones have duration while deliverables do not',
 'B',
 'A milestone is a zero-duration event marking a significant point (e.g., phase completion). A deliverable is a tangible output or product produced by project work.',
 'Process', 'Project Work'),

(@exam3,
 'A project benefits from a strategic partnership but the partner organization has different risk tolerance levels. How should this be managed?',
 'Apply your organization risk standards to the partner',
 'Establish a joint risk management approach that acknowledges and balances both organizations risk tolerances',
 'Ignore the partner risk preferences',
 'Let each organization manage their own risks independently',
 'B',
 'When partnering with organizations that have different risk tolerances, a joint risk management approach ensures alignment and prevents conflicting risk decisions.',
 'Business Environment', 'Uncertainty');
